#!/usr/bin/python
# Copyright (c) 2011
# Distilled Media Ltd.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the author nor the names of any contributors to the
#    software may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#
# Monitors updates being passed to the /update query handler
#

import httplib, sys
from lxml import etree
import os,re

hostport  = 'localhost:8080'
try:
	if os.environ['hostport']:
		hostport = os.environ['hostport']
except:
	pass

cores = ['__SINGLE_CORE__']
try:
	if os.environ['cores']:
		cores = re.split(r'\s+', os.environ['cores'])
	p = re.compile( 'solr_\w+(?<=_)' )
	filename = os.path.basename(__file__)
	core = p.sub('', filename)
	if core != filename:
        	cores = [ core ]
except:
	pass

if sys.argv[-1] == 'config':
	print "graph_title Solr Updates / Requests Per Second"
	print "graph_args -l 0"
	print "graph_vlabel ups"
	print "graph_category search"
	print "ups.label Updates per second"
	for core in cores:
                if core == '__SINGLE_CORE__':
                        core = ''
		print "%s_avg_ups.label %s Avg Requests Per Second" % (core, core)
		print "%s_ups.label %s Requests per second" % (core, core)
		print "%s_ups.type COUNTER" % core
else:
	conn = httplib.HTTPConnection( hostport )
	for core in cores:
                if core == '__SINGLE_CORE__':
                        core = coredir = '' 
                else:
                	coredir = "/%s" % core
                path = "/solr%s/admin/stats.jsp" % coredir
		conn.request("GET", path)
		res = conn.getresponse()

		if res.status == 200:
			data = res.read()

			root = etree.fromstring(data)
			elements = root.xpath('/solr/solr-info/QUERYHANDLER')
	
			for entry in elements[0].xpath('entry'):
				if entry[0].text.strip() == '/update':
					stats = entry.xpath('stats')
					for stat in stats[0]:
						if stat.get("name") == 'avgRequestsPerSecond':
							print "%s_avg_ups.value %s" % (core, stat.text.strip())
						if stat.get('name') == 'requests':
							print "%s_ups.value %s" % (core, stat.text.strip())
